[NbConvertApp] Converting notebook nb01_ale.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
[NbConvertApp] ERROR | Error while converting 'nb01_ale.ipynb'
Traceback (most recent call last):
  File "/mpcdf/soft/SLE_12/packages/x86_64/anaconda/3/2020.02/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/mpcdf/soft/SLE_12/packages/x86_64/anaconda/3/2020.02/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/mpcdf/soft/SLE_12/packages/x86_64/anaconda/3/2020.02/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/mpcdf/soft/SLE_12/packages/x86_64/anaconda/3/2020.02/lib/python3.7/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/mpcdf/soft/SLE_12/packages/x86_64/anaconda/3/2020.02/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/mpcdf/soft/SLE_12/packages/x86_64/anaconda/3/2020.02/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 316, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/mpcdf/soft/SLE_12/packages/x86_64/anaconda/3/2020.02/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/mpcdf/soft/SLE_12/packages/x86_64/anaconda/3/2020.02/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/mpcdf/soft/SLE_12/packages/x86_64/anaconda/3/2020.02/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/mpcdf/soft/SLE_12/packages/x86_64/anaconda/3/2020.02/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 448, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
# Glass brain example
from nilearn import image, plotting, reporting
img = image.load_img('../results/ale/all_z_level-cluster_corr-FWE_method-montecarlo.nii.gz')
p = plotting.plot_glass_brain(img, vmin=0, vmax=8, colorbar=True)

# Cluster table example
t = reporting.get_clusters_table(img, stat_threshold=0.001, min_distance=0)
t.hide_index()

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-6-784c9c7ae0bb>[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m [0;31m# Cluster table example[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0mt[0m [0;34m=[0m [0mreporting[0m[0;34m.[0m[0mget_clusters_table[0m[0;34m([0m[0mimg[0m[0;34m,[0m [0mstat_threshold[0m[0;34m=[0m[0;36m0.001[0m[0;34m,[0m [0mmin_distance[0m[0;34m=[0m[0;36m0[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 8[0;31m [0mt[0m[0;34m.[0m[0mhide_index[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/mpcdf/soft/SLE_12/packages/x86_64/anaconda/3/2020.02/lib/python3.7/site-packages/pandas/core/generic.py[0m in [0;36m__getattr__[0;34m(self, name)[0m
[1;32m   5272[0m             [0;32mif[0m [0mself[0m[0;34m.[0m[0m_info_axis[0m[0;34m.[0m[0m_can_hold_identifiers_and_holds_name[0m[0;34m([0m[0mname[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   5273[0m                 [0;32mreturn[0m [0mself[0m[0;34m[[0m[0mname[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 5274[0;31m             [0;32mreturn[0m [0mobject[0m[0;34m.[0m[0m__getattribute__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mname[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   5275[0m [0;34m[0m[0m
[1;32m   5276[0m     [0;32mdef[0m [0m__setattr__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mname[0m[0;34m:[0m [0mstr[0m[0;34m,[0m [0mvalue[0m[0;34m)[0m [0;34m->[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: 'DataFrame' object has no attribute 'hide_index'
AttributeError: 'DataFrame' object has no attribute 'hide_index'

srun: error: dra0232: task 0: Exited with exit code 1
srun: Terminating job step 18308966.0
